In [1]:
import numpy as np

In [2]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [3]:
np.array(['dateadu'])

array(['dateadu'], dtype='<U7')

In [4]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
np.arange(1,6,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.full(5,4.)

array([4., 4., 4., 4., 4.])

In [9]:
np.full(5,4).dtype

dtype('int64')

In [10]:
arr_1d = np.array([1,2,3,4,5])

In [11]:
arr_1d[0]

1

In [12]:
arr_1d[-1]

5

In [13]:
print(arr_1d[0:2])

[1 2]


In [14]:
print(arr_1d[2:])

[3 4 5]


In [15]:
arr = np.array([1,2,-4, 9, -16, 25])
print(arr)

[  1   2  -4   9 -16  25]


In [16]:
print(np.abs(arr))

[ 1  2  4  9 16 25]


In [17]:
print(np.fabs(arr))

[ 1.  2.  4.  9. 16. 25.]


In [19]:
arr_1 = np.arange(5)
print(arr_1)

[0 1 2 3 4]


In [21]:
arr_2 = np.arange(1,10,2)
print(arr_2)

[1 3 5 7 9]


In [22]:
print(np.add(arr_1,arr_2))

[ 1  4  7 10 13]
